### ISSUE TITLE
equations in one line

### ISSUE THREAD

**Issue by hvdmaas** [tasospsy/complexity_book#19]
some equation are on one line in html:

2.4

3.12

7.1

and derivation in section Stable and unstable fixed points

**Comment by tasospsy** [comment]
Fixed. 
Please, check if you agree with the **table** I added for the derivation in section 4.2.2

**Comment by hvdmaas** [comment]
table is great! equation 7.1 is still not ok (should  be 3 lines)
